NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.yolean2.se-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.yolean2.se-cert.pem
    OrganizationalUnitIdentifier: peer
