apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-node
  labels: &labels
    app: backend-node
spec:
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - name: node
        image: backend-node
        ports:
        - containerPort: 8080
      hostAliases:
        - ip: 10.99.195.159
          hostnames: [orderer0.yolean2ord.se]
        - ip: 10.96.150.36
          hostnames: [orderer0.yoleanord.se]
        - ip: 10.110.235.243
          hostnames: [peer0.yolean.se]
        - ip: 10.98.235.116
          hostnames: [peer1.yolean.se]
        - ip: 10.111.144.103
          hostnames: [peer0.yolean2.se]
        - ip: 10.108.11.124
          hostnames: [peer1.yolean2.se]
          
