apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-node
  labels: &labels
    app: backend-node
spec:
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - name: node
        image: backend-node
        ports:
        - containerPort: 8080
      hostAliases:
      - ip: 10.99.201.206
        hostnames: [orderer0.yolean2ord.se]
      - ip: 10.104.39.159
        hostnames: [orderer0.yoleanord.se]
      - ip: 10.99.106.90
        hostnames: [peer0.yolean.se]
      - ip: 10.111.57.94
        hostnames: [peer1.yolean.se]
      - ip: 10.96.236.250
        hostnames: [peer0.yolean2.se]
      - ip: 10.111.30.247
        hostnames: [peer1.yolean2.se]
          
