apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels: &labels
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - name: quarkus
        image: backend
        args:
          - -Dquarkus.http.port=8080
        ports:
        - containerPort: 8080