# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: YoleanOrd
    Domain: yoleanord.se
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
  - Name: Yolean2Ord
    Domain: yolean2ord.se
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
      
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: Yolean
    Domain: yolean.se
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  
  - Name: Yolean2
    Domain: yolean2.se
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1